name: Build

description: Build the source files

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Yarn install
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Yarn build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build

    - name: web-ext build
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: dist

    - name: Get package name
      id: vars
      shell: bash
      run: |
        echo "::set-output name=pkg_name::$(node -e "console.log(require('./package.json').name);")"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.vars.outputs.pkg_name }}.xpi
        path: ${{ steps.web-ext-build.outputs.target }}
