name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release Branch and Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get package data
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=pkg_version::$(node -e "console.log(require('./package.json').version);")"
          echo "::set-output name=pkg_name::$(node -e "console.log(require('./package.json').name);")"

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: web-ext lint
        uses: kewisch/action-web-ext@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cmd: lint
          channel: listed

      - name: web-ext build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build

      - name: web-ext sign
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}
          tag_name: v${{ steps.vars.outputs.pkg_version }}

      - name: Publish to AMO
        uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{39c28e80-541d-4823-9fc9-44ecae549e8f}'
          xpi: ${{ steps.web-ext-sign.outputs.target }}
          manifest: manifest.json
          api-key: ${{ secrets.AMO_SIGN_KEY }}
          api-secret: ${{ secrets.AMO_SIGN_SECRET }}
