name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Release Branch and Tag
    runs-on: ubuntu-latest
    outputs:
      tag: 'v${{ steps.vars.outputs.pkg_version }}'
    steps:
      - name: Build
        uses: ./actions/build

      - name: Get package version
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=pkg_version::$(node -e "console.log(require('./package.json').version);")"

      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.2.0
        with:
          add: 'dist'
          force: true
          message: 'Built ${{ steps.vars.outputs.sha_short }}'
          ref: 'release/v${{ steps.vars.outputs.pkg_version }}'
          tag: 'v${{ steps.vars.outputs.pkg_version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          release_name: ${{ needs.build.outputs.tag }}
          draft: false
          prerelease: false
